/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_dinpay_keyso_DinpayUtils */

#ifndef _Included_com_dinpay_keyso_DinpayUtils
#define _Included_com_dinpay_keyso_DinpayUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_dinpay_keyso_DinpayUtils
 * Method:    getSignMD
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_dinpay_keyso_DinpayUtils_getSignMD
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
